# Server Configuration
server:
  port: 8083

  error:
    include-stacktrace: always
  compression:
    enabled: true
  address: 0.0.0.0

# Spring Configuration
spring:
  jackson:
    date-format: yyyy-MM-dd
  application:
    name: bitcoincanvas
  main:
    allow-bean-definition-overriding: true

  # Database Configuration
  datasource:
    url: jdbc:mysql://180.211.137.8:3306/whatsapp
    username: root
    password: Nexalinx@!1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true
    # Hibernate
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"

  #feign.client.config.default.connectTimeout: 160000000
  #feign.client.config.default.readTimeout: 160000000

  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 500KB
      max-request-size: 500KB
      resolve-lazily: false

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000